// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upgradarr.Data;

#nullable disable

namespace Upgradarr.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206103902_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Upgradarr.Domain.Entities.QueueRecord", b =>
                {
                    b.Property<string>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Added")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RemoveAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("DownloadId");

                    b.ToTable("TrackedDownloads");
                });

            modelBuilder.Entity("Upgradarr.Domain.Entities.UpgradeState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchState")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UpgradeStates");
                });

            modelBuilder.Entity("Upgradarr.Domain.Entities.QueueRecord", b =>
                {
                    b.OwnsMany("Upgradarr.Domain.ValueObjects.QueueItemScore", "ItemScores", b1 =>
                        {
                            b1.Property<string>("QueueRecordDownloadId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("CustomFormatScore");

                            b1.Property<int>("ItemId");

                            b1.HasKey("QueueRecordDownloadId", "__synthesizedOrdinal");

                            b1.ToTable("TrackedDownloads");

                            b1
                                .ToJson("ItemScores")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("QueueRecordDownloadId");
                        });

                    b.Navigation("ItemScores");
                });
#pragma warning restore 612, 618
        }
    }
}
