// <auto-generated />
using Huntarr.Net.Api;
using Huntarr.Net.Api.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
