// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Huntarr.Net.Api.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("57f17a93-ee87-4e9d-ae29-a0b4bd00a92f"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var queueItemScore = QueueItemScoreEntityType.Create(this);
            var queueRecord = QueueRecordEntityType.Create(this);
            var upgradeState = UpgradeStateEntityType.Create(this);

            QueueItemScoreEntityType.CreateForeignKey1(queueItemScore, queueRecord);

            QueueItemScoreEntityType.CreateAnnotations(queueItemScore);
            QueueRecordEntityType.CreateAnnotations(queueRecord);
            UpgradeStateEntityType.CreateAnnotations(upgradeState);

            AddAnnotation("ProductVersion", "10.0.2");
        }
    }
}
