# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      if: github.event_name == 'push'
      run: dotnet publish Huntarr.Net.Api/Huntarr.Net.Api.csproj -c Release -o ./publish
    - name: Upload artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: upgradarr
        path: ./publish
